version: 2.1

commands:
  run-tests:
    description: "Run tests"
    steps:
      - run: echo 'Start unit test'
      - run: echo 'Done !!'

jobs:
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run-tests

workflows:
  version: 2.1
  playground:
    jobs:
      - test
