version: 2.1

commands:
  test:
    description: "Run tests"
    steps:
      - run:
        name: Unit Test
        command: |
          echo 'Start unit test'
          echo 'Done !!'

jobs:
  test:
    steps:
      - test

workflow:
  version: 2.1
  playground:
    jobs:
      - test:
